apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gitops-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shravani556/argocd-minikube-demo.git 
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc 
    namespace: gitops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true