apiVersion: apps/v1
kind: Deployment

metadata:
  name: html-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: html-demo

  template:
    metadata:
      labels:
        app: html-demo

    spec:
      # Kubernetes uses this secret to authenticate
      # when pulling the private Docker image from Nexus.
      imagePullSecrets:
        - name: nexus-registry

      containers:
        - name: html-app

          # CI will automatically update this image version.
          image: 192.168.49.1:8081/docker-hosted/html-gitops:1.0.9

          # Pull from the registry when the image is not
          # already available locally.
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 50m
              memory: 32Mi

            limits:
              cpu: 200m
              memory: 128Mi
